output   = "mymodels"
wipe     = true
no-tests = true

[psql]
  dbname = "social_network"
  host   = "localhost"
  port   = 5432
  user    = "postgres"
  pass    = "postgres"
  schema = "public"
  blacklist = ["migrations", "other"]
  sslmode = "disable"